export const core2024 = [
  {
    id: 1,
    photo: 'https://randomuser.me/api/portraits/women/65.jpg',
    video: '',
    name: "Megha Arora",
    postition: "Team Lead",
    role: "Team Lead",
    description: "Architect of creative chaos.",
    linkedin: "https://linkedin.com/in/meghaarora",
    github: "https://github.com/meghaarora",
    insta: "https://instagram.com/megha.leads",
    contact: "megha.arora@example.com",
    hoverColor: "hover:bg-purple-600",
  },
  {
    id: 2,
    photo: 'https://randomuser.me/api/portraits/men/60.jpg',
    video: '',
    name: "Rohit Das",
    postition: "DevOps Engineer",
    role: "Engineering",
    description: "Keeps the pipes clean and code flowing.",
    linkedin: "https://linkedin.com/in/rohitdas",
    github: "https://github.com/rohitdas",
    insta: "https://instagram.com/rohit.devops",
    contact: "rohit.das@example.com",
    hoverColor: "hover:bg-gray-700",
  },
  {
    id: 3,
    photo: 'https://randomuser.me/api/portraits/women/52.jpg',
    video: '',
    name: "Isha Kapoor",
    postition: "UI Developer",
    role: "Design",
    description: "Smooth UI, smoother UX.",
    linkedin: "https://linkedin.com/in/ishakapoor",
    github: "https://github.com/ishakapoor",
    insta: "https://instagram.com/isha.codes",
    contact: "isha.kapoor@example.com",
    hoverColor: "hover:bg-pink-500",
  },
  {
    id: 4,
    photo: 'https://randomuser.me/api/portraits/men/28.jpg',
    video: '',
    name: "Aman Sheikh",
    postition: "Outreach Manager",
    role: "Outreach",
    description: "Bridges people with purpose.",
    linkedin: "https://linkedin.com/in/amansheikh",
    github: "",
    insta: "https://instagram.com/aman.outreach",
    contact: "aman.sheikh@example.com",
    hoverColor: "hover:bg-blue-500",
  },
  {
    id: 5,
    photo: 'https://randomuser.me/api/portraits/women/30.jpg',
    video: '',
    name: "Tanya Roy",
    postition: "Content Lead",
    role: "Content",
    description: "Words are her superpower.",
    linkedin: "https://linkedin.com/in/tanyaroy",
    github: "",
    insta: "https://instagram.com/tanya.content",
    contact: "tanya.roy@example.com",
    hoverColor: "hover:bg-yellow-500",
  },
  {
     id: 2,
    photo: 'https://randomuser.me/api/portraits/women/55.jpg',
    video: '',
    name: "Divya Nair",
    postition: "UI/UX Designer",
    role: "Design",
    description: "Creates harmony in every frame.",
    linkedin: "https://linkedin.com/in/divyanair",
    github: "",
    insta: "https://instagram.com/divya.design",
    contact: "divya.nair@example.com",
    hoverColor: "hover:bg-pink-600",
  },
  {
    id: 3,
    photo: 'https://randomuser.me/api/portraits/men/35.jpg',
    video: '',
    name: "Siddharth Rao",
    postition: "Full Stack Developer",
    role: "Engineering",
    description: "Merges frontend magic with backend logic.",
    linkedin: "https://linkedin.com/in/siddrao",
    github: "https://github.com/siddrao",
    insta: "https://instagram.com/sidd.codes",
    contact: "siddharth.rao@example.com",
    hoverColor: "hover:bg-green-600",
  },
  {
    id: 4,
    photo: 'https://randomuser.me/api/portraits/women/47.jpg',
    video: '',
    name: "Anjali Mishra",
    postition: "Marketing Head",
    role: "Marketing",
    description: "Tells stories that stick.",
    linkedin: "https://linkedin.com/in/anjalimishra",
    github: "",
    insta: "https://instagram.com/anjali.markets",
    contact: "anjali.mishra@example.com",
    hoverColor: "hover:bg-red-600",
  },
  {
    id: 5,
    photo: 'https://randomuser.me/api/portraits/men/40.jpg',
    video: '',
    name: "Yash Patel",
    postition: "Content Creator",
    role: "Content",
    description: "Turns ideas into viral reels.",
    linkedin: "https://linkedin.com/in/yashpatel",
    github: "",
    insta: "https://instagram.com/yash.content",
    contact: "yash.patel@example.com",
    hoverColor: "hover:bg-yellow-400",
  },
];

export const core2023 = [
  {
    id: 1,
    photo: 'https://randomuser.me/api/portraits/men/50.jpg',
    video: '',
    name: "Karan Mehta",
    postition: "Team Lead",
    role: "Team Lead",
    description: "Built teams, broke limits.",
    linkedin: "https://linkedin.com/in/karanmehta",
    github: "https://github.com/karanmehta",
    insta: "https://instagram.com/karan.leads",
    contact: "karan.mehta@example.com",
    hoverColor: "hover:bg-blue-600",
  },
  {
    id: 2,
    photo: 'https://randomuser.me/api/portraits/women/55.jpg',
    video: '',
    name: "Divya Nair",
    postition: "UI/UX Designer",
    role: "Design",
    description: "Creates harmony in every frame.",
    linkedin: "https://linkedin.com/in/divyanair",
    github: "",
    insta: "https://instagram.com/divya.design",
    contact: "divya.nair@example.com",
    hoverColor: "hover:bg-pink-600",
  },
  {
    id: 3,
    photo: 'https://randomuser.me/api/portraits/men/35.jpg',
    video: '',
    name: "Siddharth Rao",
    postition: "Full Stack Developer",
    role: "Engineering",
    description: "Merges frontend magic with backend logic.",
    linkedin: "https://linkedin.com/in/siddrao",
    github: "https://github.com/siddrao",
    insta: "https://instagram.com/sidd.codes",
    contact: "siddharth.rao@example.com",
    hoverColor: "hover:bg-green-600",
  },
  {
    id: 4,
    photo: 'https://randomuser.me/api/portraits/women/47.jpg',
    video: '',
    name: "Anjali Mishra",
    postition: "Marketing Head",
    role: "Marketing",
    description: "Tells stories that stick.",
    linkedin: "https://linkedin.com/in/anjalimishra",
    github: "",
    insta: "https://instagram.com/anjali.markets",
    contact: "anjali.mishra@example.com",
    hoverColor: "hover:bg-red-600",
  },
  {
    id: 5,
    photo: 'https://randomuser.me/api/portraits/men/40.jpg',
    video: '',
    name: "Yash Patel",
    postition: "Content Creator",
    role: "Content",
    description: "Turns ideas into viral reels.",
    linkedin: "https://linkedin.com/in/yashpatel",
    github: "",
    insta: "https://instagram.com/yash.content",
    contact: "yash.patel@example.com",
    hoverColor: "hover:bg-yellow-400",
  },
];
