export const core = [
  {
    id: 1,
    photo: 'https://randomuser.me/api/portraits/men/32.jpg',
    video: '',
    name: "Aarav Sharma",
    postition: "Team Lead",
    description: "Spreading vibes like butter on aloo paratha.",
    linkedin: "https://linkedin.com/in/aaravsharma",
    github: "https://github.com/aaravsharma",
    insta: "https://instagram.com/aarav.codes",
    contact: "aarav.sharma@example.com",
    hoverColor: "hover:bg-blue-500",
  },
  {
    id: 2,
    photo: 'https://randomuser.me/api/portraits/women/44.jpg',
    video: '',
    name: "Priya Verma",
    postition: "Frontend Developer",
    description: "Turns pixels into perfection.",
    linkedin: "https://linkedin.com/in/priyaverma",
    github: "https://github.com/priyaverma",
    insta: "https://instagram.com/priya.ui",
    contact: "priya.verma@example.com",
    hoverColor: "hover:bg-pink-500",
  },
  {
    id: 3,
    photo: 'https://randomuser.me/api/portraits/men/45.jpg',
    video: '',
    name: "Rahul Kapoor",
    postition: "Backend Developer",
    description: "Eats bugs for breakfast. Node.js is his weapon.",
    linkedin: "https://linkedin.com/in/rahulkapoor",
    github: "https://github.com/rahulkapoor",
    insta: "https://instagram.com/rahul.codes",
    contact: "rahul.kapoor@example.com",
    hoverColor: "hover:bg-gray-700",
  },
  {
    id: 4,
    photo: 'https://randomuser.me/api/portraits/women/60.jpg',
    video: '',
    name: "Sneha Joshi",
    postition: "Design Lead",
    description: "Paints the web with colors and purpose.",
    linkedin: "https://linkedin.com/in/snehajoshi",
    github: "",
    insta: "https://instagram.com/sneha.designs",
    contact: "sneha.joshi@example.com",
    hoverColor: "hover:bg-indigo-500",
  },
  {
    id: 5,
    photo: 'https://randomuser.me/api/portraits/men/66.jpg',
    video: '',
    name: "Manish Sinha",
    postition: "Content Strategist",
    description: "Writes words that whisper and shout.",
    linkedin: "https://linkedin.com/in/manishsinha",
    github: "",
    insta: "https://instagram.com/manish.content",
    contact: "manish.sinha@example.com",
    hoverColor: "hover:bg-yellow-500",
  },
];

export const volunteer = [
  {
    id: 1,
    photo: 'https://randomuser.me/api/portraits/men/52.jpg',
    name: "Ankit Rawat",
    postition: "Outreach Volunteer",
    description: "Connecting dots and people.",
    linkedin: "https://linkedin.com/in/ankitrawat",
    github: "",
    insta: "https://instagram.com/ankit.reach",
    contact: "ankit.rawat@example.com",
    hoverColor: "hover:bg-teal-500",
  },
  {
    id: 2,
    photo: 'https://randomuser.me/api/portraits/women/23.jpg',
    name: "Megha Nair",
    postition: "Event Volunteer",
    description: "First to arrive, last to leave.",
    linkedin: "",
    github: "",
    insta: "https://instagram.com/megha.events",
    contact: "megha.nair@example.com",
    hoverColor: "hover:bg-rose-500",
  },
  {
    id: 3,
    photo: 'https://randomuser.me/api/portraits/men/33.jpg',
    name: "Rohan Mehta",
    postition: "Teaching Volunteer",
    description: "Simplifies hard things with a smile.",
    linkedin: "https://linkedin.com/in/rohanmehta",
    github: "https://github.com/rohan-teaches",
    insta: "",
    contact: "rohan.mehta@example.com",
    hoverColor: "hover:bg-lime-500",
  },
  {
    id: 4,
    photo: 'https://randomuser.me/api/portraits/women/37.jpg',
    name: "Aisha Khan",
    intrest: "Management",
    description: "Keeps everything running smoothly.",
    linkedin: "https://linkedin.com/in/aishakhan",
    github: "",
    insta: "https://instagram.com/aisha.manage",
    contact: "aisha.khan@example.com",
    hoverColor: "hover:bg-purple-500",
  },
];
